### PR TITLE
Replace the local HTTP server

### PR DESCRIPTION
**Pull request by dotmonkey**
http server is not needed now for EPUB publications.

### CODE REVIEW

**Review by mickael-menu — CHANGES_REQUESTED** [review]
Thanks for taking a look at this issue, that's a nice first shot.

There's a number of issues to address before we can merge this feature in:

* The `Publication` should not expose a new public `serverFetcher` property.
* The code handling the injection currently in the server should be moved to the navigator (`HtmlInjector`) instead of relying on the current `Server` implementation, which will be deprecated.
* Byte range requests don't seem to be handled in the HTTP response, which will be important for serving video or audio with EPUB 3.
* To serve the assets, maybe `WebViewAssetLoader` would be more suitable?

**Comment by dotmonkey** [comment]
Thanks for review.
some reasons about the issues: 
- HtmlInjector is now in streamer module, and not visible to navigator module. 
- HtmlInjector needs field userPropertiesPath and customResources which is also not available in class R2EpubPageFragment or EpubNavigatorFragment.
- when range filed of ResourceInputStream object is null,ResourceInputStream will auto detect the length for the resource. wether browser read a byte or ByteArray one time is determined by the browser.
- WebViewAssetLoader just process one path:assets, and it use URLConnection.guessContentTypeFromName to guess mime type, so js and font files will got null mime type.

**Comment by mickael-menu** [comment]
Thanks for the additional details,

I'm working on a new Presentation API which will render `userPropertiesPath` obsolete. It will probably be merged early next year, I think we can revisit your PR then to use this new API instead which will remove any dependency on the streamer.

**Comment by dotmonkey** [comment]
OK

**Pull request closed without merging**
