### PR TITLE
Licenses : Add Accept header on fetch status document request

### PR DESCRIPTION
**Pull request by hmoukaideche-vivlio**
# Licenses : Add Accept header on fetch status document request

### Fixed

I added an `Accept` header on status document request, since some servers requires this header to accept this request.
`Accept` is now set to `application/json` since it's a json document.

### CODE REVIEW

**Review by mickael-menu — CHANGES_REQUESTED** [review]
Thanks for tackling that 🙏 

I think we should use the media types declared in the specifications instead of `application/json` though:

* License: [`application/vnd.readium.lcp.license.v1.0+json`](https://readium.org/lcp-specs/releases/lcp/latest.html#32-content-conformance)
* Status Document: [`application/vnd.readium. license.status.v1.0+json`](https://readium.org/lcp-specs/releases/lsd/latest.html#35-renewing-a-license)

**Comment by hmoukaideche-vivlio** [comment]
I made the requested changes, if it's ok I will make the equivalent changes to swift-toolkit project 👍

**Comment by mickael-menu** [comment]
Looking good thanks, I'll test and merge this Friday.

>  if it's ok I will make the according changes to swift-toolkit project as well

Sure, thank you!

**Review by mickael-menu — APPROVED** [review]
Thank you!

**Pull request merged**
