### PR TITLE
Improve loading of EPUB reflowable resources

### PR DESCRIPTION
**Pull request by mickael-menu**
#### Navigator

* Improve loading of EPUB reflowable resources.
    * Resources are hidden until fully loaded and positioned.
    * Intermediary locators are not broadcasted as `currentLocator` anymore while loading a resource.
    * Improved accuracy when jumping to the middle of a large resource.
    * `EpubNavigatorFragment.PaginationListener.onPageLoaded()` is now called only a single time, for the currently visible page.
    * `VisualNavigator.Listener.onTap()` is called even when a resource is not fully loaded.

### CODE REVIEW

**Review by aferditamuriqi — APPROVED** [review]
Just from review it looks good to me, please note that i didn't have a chance to actually test the code.

**Comment by mickael-menu** [comment]
@aferditamuriqi Thanks, I'll have a version in production this week using this code and see if we get some feedback for these changes.

**Comment by mickael-menu** [comment]
@aferditamuriqi Quentin shared a technique that seems to make the delay unnecessary! It's basically this:

```kotlin
            override fun onPageFinished(view: WebView?, url: String?) {
                super.onPageFinished(view, url)

                webView.listener.onResourceLoaded(link, webView, url)

                // To make sure the page is properly laid out before jumping to the target locator,
                // we execute a dummy JavaScript and wait for the callback result.
                webView.evaluateJavascript("true") {
                    viewLifecycleOwner.lifecycleScope.launchWhenCreated {
                        onLoadPage()
                    }
                }
            }
```

I got some great results during my tests, but I would be interested in having your feedback as well with your own test books.

**Comment by aferditamuriqi** [comment]
> @aferditamuriqi Quentin shared a technique that seems to make the delay unnecessary! It's basically this:
> 
> ```kotlin
>             override fun onPageFinished(view: WebView?, url: String?) {
>                 super.onPageFinished(view, url)
> 
>                 webView.listener.onResourceLoaded(link, webView, url)
> 
>                 // To make sure the page is properly laid out before jumping to the target locator,
>                 // we execute a dummy JavaScript and wait for the callback result.
>                 webView.evaluateJavascript("true") {
>                     viewLifecycleOwner.lifecycleScope.launchWhenCreated {
>                         onLoadPage()
>                     }
>                 }
>             }
> ```
> 
> I got some great results during my tests, but I would be interested in having your feedback as well with your own test books.

@mickael-menu i haven't yet gotten a chance to test this, but sure would like to, i will be able to do that within this two weeks.

**Pull request merged**
